# Generated by Django 4.2.5 on 2023-09-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_read_alter_notification_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(null=True),
        ),
    ]
