# Generated by Django 4.2.5 on 2023-09-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_topic_text_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='text',
        ),
        migrations.AddField(
            model_name='topic',
            name='body',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
