# Generated by Django 4.2.5 on 2023-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_topic_text_topic_body_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='choices',
            field=models.JSONField(),
        ),
    ]
