# Generated by Django 4.2.5 on 2023-09-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_comment_creator_poll_creator_topic_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
