# Generated by Django 4.2.5 on 2023-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_topic_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voted',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='voted',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
